name: gcp-workload-identity-federation
description: Grant pipelines access to Google Cloud resources using Workload Identity Federation
author: https://github.com/buildkite-plugins
public: true
requirements:
  - bash
  - buildkite-agent
configuration:
  properties:
    audience:
      type: string
    claims:
      type: array
      items:
        type: string
    gcp-project-id:
      type: string
    mode:
      type: string
      enum:
        - 'ro'
        - 'rw'
      default: 'rw'
    hook:
      type: string
    lifetime:
      type: number
    render-command:
      type: string
    service-account:
      type: string
  required:
    - gcp-project-id
  additionalProperties: false
