steps:
  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.1.0: ~

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.2.0:
          id: gcp-workload-identity-federation

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**
