#!/bin/bash

set -euo pipefail

# run plugin in the environment hook only if explicitly configured
if [[ "${BUILDKITE_PLUGIN_GCP_WORKLOAD_IDENTITY_FEDERATION_HOOK:-pre-command}" == "environment" ]]; then
  echo "Running in the environment hook"
else
  echo "Skipping environment hook"
  exit 0
fi

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"
