#!/bin/bash

set -euo pipefail

# this should run regardless of the hook configuration as it will need to be
# cleaned up in both cases.
if [[ -n "${BUILDKITE_OIDC_TMPDIR:-}" ]]; then
  rm -rf "$BUILDKITE_OIDC_TMPDIR"

  echo "Removed credentials from $BUILDKITE_OIDC_TMPDIR"
fi
